
const PHOTOS = {
    PHOTO1: require("./product_1.png"),
    PHOTO2: require("./product_2.png"),
    PHOTO3: require("./product_3.png"),
    PHOTO4: require("./product_4.png"),
    PHOTO5: require("./product_5.png"),
    PHOTO6: require("./product_6.png"),
    PHOTO7: require("./product_7.png"),
    PHOTO8: require("./product_8.png"),
    PHOTO9: require("./product_9.png"),
    PHOTO10: require('./product_10.png'),
    PHOTO11: require("./product_11.png"),
    PHOTO12: require("./product_12.png"),
    PHOTO13: require("./product_13.png"),
    PHOTO14: require("./product_14.png"),
    PHOTO15: require("./product_15.png"),
    PHOTO16: require("./product_16.png"),
    PHOTO17: require("./product_17.png"),
    PHOTO18: require("./product_18.png"),
    PHOTO19: require("./product_19.png"),
    PHOTO20: require("./product_20.png"),
    PHOTO21: require("./product_21.png"),
    PHOTO22: require("./product_22.png"),
    PHOTO23: require("./product_23.png"),
    PHOTO24: require("./product_24.png"),
    PHOTO25: require("./product_25.png"),
    PHOTO26: require("./product_26.png"),
    PHOTO27: require("./product_27.png"),
    PHOTO28: require("./product_28.png"),
    PHOTO29: require("./product_29.png"),
    PHOTO30: require("./product_30.png"),
    PHOTO31: require("./product_31.png"),
    PHOTO32: require("./product_32.png"),
    PHOTO33: require("./product_33.png"),
    PHOTO34: require("./product_34.png"),
    PHOTO35: require("./product_35.png"),
    PHOTO36: require("./product_36.png"),

    //EXTRAS
    BANNER1: require("./banner1.png"),
    BANNER2: require("./banner2.png"),
    BANNER3: require("./banner3.png"),
    LOGO:    require("./budget mart logo.png"),
    EXCLUS:  require("./exclusive_image.png"),
    HERO:    require("./group-four-women-walk-with-shopping-bags-mall_583952-10219-removebg-preview.png"),
    CART_CROSS: require("./cart_cross_icon.png"),
    WAVE: require("./waving-hand.1024.png"),
};

export default PHOTOS;